owner: thoth-pub
repo: status

assignees:
  - ja573

sites:
  - name: Thoth APP
    url: https://thoth.pub/admin
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth GraphQL API
    url: https://api.thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth Export API
    url: https://export.thoth.pub
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth Website
    url: https://thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Strapi
    url: https://cms.thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Nextcloud
    url: https://cloud.obpcloud.org/status.php
    icon: https://cdn.thoth.pub/thoth_logo.png
    expectedStatusCodes:
      - 200
      - 400
  - name: Mattermost
    url: https://mattermost.obpcloud.org
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Matomo
    url: https://analytics.openbookpublishers.com/index.php?module=Login
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Matomo Tracker API
    url: https://analytics.openbookpublishers.com/matomo.php
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: OBC Nextcloud
    url: https://cloud.openbookcollective.org/status.php
    icon: https://openbookcollective.org/static/img/favicon.ico
    expectedStatusCodes:
      - 200
      - 400

status-website:
  cname: status.thoth.pub
  logoUrl: https://cdn.thoth.pub/thoth_logo.png
  favicon: https://cdn.thoth.pub/thoth_logo.png
  name: Thoth Status
  introTitle: "Thoth Status Dashboard"
  introMessage: You can find more information about Thoth on [thoth.pub](https://thoth.pub/).
  scripts:
    - src: https://cdn.thoth.pub/analytics.js
      async: true
  navbar:
    - title: Status
      href: /
    - title: Support
      href: mailto:support@thoth.pub
    - title: GitHub
      href: https://github.com/thoth-pub

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
