owner: thoth-pub
repo: status

assignees:
  - ja573

sites:
  - name: Thoth APP
    url: https://thoth.pub/admin
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth GraphQL API
    url: https://api.thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth Export API
    url: https://export.thoth.pub
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Thoth Website
    url: https://thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Strapi
    url: https://cms.thoth.pub/
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Nextcloud
    url: https://cloud.obpcloud.org/status.php
    icon: https://cdn.thoth.pub/thoth_logo.png
    expectedStatusCodes:
      - 200
      - 400
  - name: Mattermost
    url: https://mattermost.obpcloud.org
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: Matomo
    url: https://analytics.openbookpublishers.com/index.php?module=Login
    icon: https://cdn.thoth.pub/thoth_logo.png
  - name: OBC Nextcloud
    url: https://cloud.openbookcollective.org/status.php
    icon: https://openbookcollective.org/static/img/favicon.ico
    expectedStatusCodes:
      - 200
      - 400

status-website:
  themeUrl: https://status.thoth.pub/thoth.css
  cname: status.thoth.pub
  logoUrl: https://cdn.thoth.pub/thoth_logo.png
  favicon: https://cdn.thoth.pub/thoth_logo.png
  name: Thoth Status
  introTitle: "Thoth Status Dashboard"
  introMessage: Real-time updates on Thoth's services' uptime, incidents, and maintenance schedules.<br>You can find more information about Thoth on [thoth.pub](https://thoth.pub/).
  scripts:
    - src: https://cdn.thoth.pub/analytics.js
      async: true
  navbar:
    - title: Status
      href: /
    - title: Support
      href: mailto:support@thoth.pub
    - title: GitHub
      href: https://github.com/thoth-pub

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)<br>Copyright © 2024 Thoth Open Metadata. Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](http://creativecommons.org/licenses/by/4.0/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
