# Change these first
owner: thoth-pub # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Thoth APP
    url: https://thoth.pub/admin
  - name: Thoth GraphQL API
    url: https://api.thoth.pub/
  - name: Thoth Export API
    url: https://export.thoth.pub
  - name: Thoth Website
    url: https://thoth.pub/
  - name: Nextcloud
    url: https://cloud.obpcloud.org
  - name: Mattermost
    url: https://mattermost.obpcloud.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thoth.pub
  # baseUrl: /status
  logoUrl: https://cdn.thoth.pub/thoth_logo.png
  name: Thoth Status
  introTitle: "Thoth Status Dashboard"
  introMessage: You can find more information about Thoth on [thoth.pub](https://thoth.pub/).
  navbar:
    - title: Status
      href: /
    - title: Support
      href: mailto:support@thoth.pub
    - title: GitHub
      href: https://github.com/thoth-pub

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
